// rspack/solid/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal } from 'solid-js';
import Message from './Message';
function App() {
  const [count, setCount] = createSignal(1);
  const increment = () => setCount(count() + 1);
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
        <button type="button" onClick={increment}>
          {count()}
        </button>
        <Message />
      </header>
    </div>
  );
}

export default App;

// rspack/preact-refresh/src/App.jsx
import React from 'react';
import { useState, useEffect } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [count, setCount] = useState(1);
  useEffect(() => {
    const timer = setInterval(() => {
      setCount((x) => x + 1);
    }, 1000);
    return () => {
      clearInterval(timer);
    };
  }, []);
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <div>count: {count}</div>
        <a
          className="App-link"
          href="https://preactjs.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Preact
        </a>
      </header>
    </div>
  );
}

export default App;
