// rsbuild/stylex/src/App.tsx
import stylex from '@stylexjs/stylex';

const styles = stylex.create({
  content: {
    display: 'flex',
    minHeight: '100vh',
    lineHeight: 1.1,
    textAlign: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  title: {
    fontSize: '3.6rem',
    fontWeight: 700,
  },
  description: {
    fontSize: '1.2rem',
    fontWeight: 400,
    opacity: 0.5,
  },
});

const App = () => {
  return (
    <div {...stylex.props(styles.content)}>
      <h1 {...stylex.props(styles.title)}>Rsbuild with React</h1>
      <p {...stylex.props(styles.description)}>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;

// rsbuild/vue3-auto-import/src/App.vue
<template>
  <div class="content">
    <h1>{{ title }}</h1>
    <p>Start building amazing things with Rsbuild.</p>
  </div>
</template>

<script setup lang="ts">
const title = ref("Rsbuild with Vue");
</script>

<style scoped>
.content {
  display: flex;
  min-height: 100vh;
  line-height: 1.1;
  text-align: center;
  flex-direction: column;
  justify-content: center;
}

.content h1 {
  font-size: 3.6rem;
  font-weight: 700;
}

.content p {
  font-size: 1.2rem;
  font-weight: 400;
  opacity: 0.5;
}
</style>
