// rsbuild/vue3-auto-import/src/App.vue
<template>
  <div class="content">
    <h1>{{ title }}</h1>
    <p>Start building amazing things with Rsbuild.</p>
  </div>
</template>

<script setup lang="ts">
const title = ref("Rsbuild with Vue");
</script>

<style scoped>
.content {
  display: flex;
  min-height: 100vh;
  line-height: 1.1;
  text-align: center;
  flex-direction: column;
  justify-content: center;
}

.content h1 {
  font-size: 3.6rem;
  font-weight: 700;
}

.content p {
  font-size: 1.2rem;
  font-weight: 400;
  opacity: 0.5;
}
</style>

// rsbuild/react-tailwindcss/src/App.tsx
import "./App.css";

const App = () => {
  return (
    <div className="flex flex-col justify-center items-center min-h-screen text-center">
      <h1 className="text-6xl font-bold leading-normal">Rsbuild with React</h1>
      <p className="text-lg font-normal text-gray-500 leading-normal">
        Start building amazing things with Rsbuild.
      </p>
    </div>
  );
};

export default App;
