// rspack/preact/src/App.jsx
import React from 'react';
import { useState, useEffect } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [count, setCount] = useState(1);
  useEffect(() => {
    setInterval(() => {
      setCount((x) => x + 1);
    }, 1000);
  }, []);
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <div>count: {count}</div>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

// rspack/vue3-tsx/src/App.tsx
import { FunctionalComponent, ref } from 'vue';
import vueLogo from './assets/vue.svg';
import Button from './Button.vue';
import './App.css';

export default {
  name: 'App',

  setup() {
    const count = ref(0);
    const add = () => count.value++;

    const CounterButton: FunctionalComponent<{
      onClick: () => void;
      value: number;
    }> = ({ onClick, value }) => {
      return <button onClick={onClick}>count is {value}</button>;
    };

    return () => (
      <div class="App">
        <h1>Hello world!</h1>
        <div>
          <a href="https://vuejs.org" target="_blank">
            <img src={vueLogo} class="logo vue" alt="Vue logo" />
          </a>
        </div>
        <h1>Rspack + Vue JSX</h1>
        <div class="card">
          <CounterButton onClick={add} value={count.value} />
        </div>
        <Button></Button>
      </div>
    );
  },
};
